# ---------- Build Stage ----------
FROM node:18 AS build-stage

WORKDIR /app

COPY bitefront/package*.json ./
RUN npm install

COPY bitefront/. .
# Inject React env variable
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

RUN npm run build

# ---------- Run Stage ----------
FROM tomcat:9.0

RUN rm -rf /usr/local/tomcat/webapps/ROOT
COPY --from=build-stage /app/build /usr/local/tomcat/webapps/ROOT/

EXPOSE 8080
CMD ["catalina.sh", "run"]
